#pragma once

static const std::string defaultConfigName = "HitScoreVisualizerConfig (default).json";

static const std::string defaultConfigText = "{"
"  \"isDefaultConfig\": true,"
"  \"useFixedPos\": false,"
"  \"fixedPosX\": 0.0,"
"  \"fixedPosY\": 0.0,"
"  \"fixedPosZ\": 0.0,"
"  \"timeDependencyDecimalPrecision\": 1,"
"  \"timeDependencyDecimalOffset\": 2,"
"  \"judgments\": ["
"    {"
"      \"threshold\": 115,"
"      \"text\": \"%BFantastic%A%n%s\","
"      \"color\": ["
"        1.0,"
"        1.0,"
"        1.0,"
"        1.0"
"      ],"
"      \"fade\": false"
"    },"
"    {"
"      \"threshold\": 101,"
"      \"text\": \"<size=80%>%BExcellent%A</size>%n%s\","
"      \"color\": ["
"        0.0,"
"        1.0,"
"        0.0,"
"        1.0"
"      ],"
"      \"fade\": false"
"    },"
"    {"
"      \"threshold\": 90,"
"      \"text\": \"<size=80%>%BGreat%A</size>%n%s\","
"      \"color\": ["
"        1.0,"
"        0.980392158,"
"        0.0,"
"        1.0"
"      ],"
"      \"fade\": false"
"    },"
"    {"
"      \"threshold\": 80,"
"      \"text\": \"<size=80%>%BGood%A</size>%n%s\","
"      \"color\": ["
"        1.0,"
"        0.6,"
"        0.0,"
"        1.0"
"      ],"
"      \"fade\": true"
"    },"
"    {"
"      \"threshold\": 60,"
"      \"text\": \"<size=80%>%BDecent%A</size>%n%s\","
"      \"color\": ["
"        1.0,"
"        0.0,"
"        0.0,"
"        1.0"
"      ],"
"      \"fade\": true"
"    },"
"    {"
"      \"threshold\": 0,"
"      \"text\": \"<size=80%>%BWay Off%A</size>%n%s\","
"      \"color\": ["
"        0.5,"
"        0.0,"
"        0.0,"
"        1.0"
"      ],"
"      \"fade\": true"
"    }"
"  ],"
"  \"beforeCutAngleJudgments\": ["
"    {"
"      \"threshold\": 70,"
"      \"text\": \"+\""
"    },"
"    {"
"      \"threshold\": 0,"
"      \"text\": \" \""
"    }"
"  ],"
"  \"accuracyJudgments\": ["
"    {"
"      \"threshold\": 15,"
"      \"text\": \" + \""
"    },"
"    {"
"      \"threshold\": 0,"
"      \"text\": \" \""
"    }"
"  ],"
"  \"afterCutAngleJudgments\": ["
"    {"
"      \"threshold\": 30,"
"      \"text\": \" + \""
"    },"
"    {"
"      \"threshold\": 0,"
"      \"text\": \" \""
"    }"
"  ],"
"  \"chainHeadJudgments\": ["
"    {"
"      \"threshold\": 75,"
"      \"text\": \"%BFantastic%n%s\","
"      \"color\": ["
"         1,"
"         1,"
"         1,"
"         1"
"       ],"
"       \"fade\": true"
"    },"
"    {"
"      \"threshold\": 65,"
"      \"text\": \"<size=80%>%BExcellent</size>%n%s\","
"      \"color\": ["
"         0,"
"         1,"
"         0,"
"         1"
"       ],"
"       \"fade\": true"
"    },"
"    {"
"      \"threshold\": 50,"
"      \"text\": \"<size=80%>%BGreat</size>%n%s\","
"      \"color\": ["
"         1,"
"         0.980392158,"
"         0,"
"         1"
"       ],"
"       \"fade\": true"
"    },"
"    {"
"      \"threshold\": 30,"
"      \"text\": \"<size=80%>%BGood</size>%n%s\","
"      \"color\": ["
"         1,"
"         0.6,"
"         0,"
"         1"
"       ],"
"       \"fade\": true"
"    },"
"    {"
"      \"threshold\": 10,"
"      \"text\": \"<size=80%>%BDecent</size>%n%s\","
"      \"color\": ["
"         1,"
"         0,"
"         0,"
"         1"
"       ],"
"       \"fade\": true"
"    },"
"    {"
"      \"threshold\": 0,"
"      \"text\": \"<size=80%>%BWay Off</size>%n%s\","
"      \"color\": ["
"         0.5,"
"         0,"
"         0,"
"         1"
"       ],"
"       \"fade\": true"
"    },"
"  ],"
"  \"chainLinkDisplay\": {"
"    \"text\": \"%s\","
"    \"color\": ["
"      0,"
"      1,"
"      0,"
"      1"
"    ],"
"  },"
"  \"timeDependencyJudgments\": null"
"}";